# adapted from ../../../../doc/spec/Makefile
PREFIX          = ../../../..
include $(PREFIX)/doc/Makefile.vars

# 	The name of your master tex file without ending .tex
TARGET = codeml #errata

# the macros from the OMDoc repository
OSTY.base	= listings lstpatch lstomdoc ed draftstamp acronyms ded myref

all:	$(PDF)
include $(PREFIX)/doc/Makefile.in

